version: '2'

services:
  services:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres@2023'
    volumes:
      - ./Database/01-sensordb.sql:/docker-entrypoint-initdb.d/01-sensordb.sql
      - ./Database/02-sensordb.sql:/docker-entrypoint-initdb.d/02-sensordb.sql

volumes:
  database_data:
    driver: local